import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../src/finance.html',import.meta.url),'utf8');
function fn(name){const lines=source.split('\n'),i=lines.findIndex(l=>l.startsWith(`function ${name}(`));if(lines[i].endsWith('}'))return lines[i];return lines.slice(i,lines.findIndex((l,j)=>j>i&&l==='}')+1).join('\n');}
function runtime(fail=false){const stored=new Map([['fin_accounts',JSON.stringify([{id:'everyday',name:'Everyday',openBal:100}])],['fin_txns',JSON.stringify([{id:'t',acct:'everyday',date:'2026-09-28',amount:-10}])]]);let failed=false;
 const storage={getItem:k=>stored.get(k)??null,setItem(k,v){if(fail&&k==='fin_txns'&&!failed){failed=true;throw Error('quota');}stored.set(k,v);},removeItem:k=>stored.delete(k)};
 const model=vm.createContext({ACCTS:JSON.parse(stored.get('fin_accounts')),TXNS:JSON.parse(stored.get('fin_txns')),K_ACCTS:'fin_accounts',K_TXNS:'fin_txns',window:{},localStorage:storage,todayISO:()=> '2026-09-29'});
 vm.runInContext(fn('saveAtomic')+';'+fn('balance')+';function acctById(id){return ACCTS.find(x=>x.id===id)}',model);
 const w=model.window;w.eval=code=>vm.runInContext(code,model);const root={document:{getElementById:()=>({contentWindow:w}),dispatchEvent(){}},localStorage:storage};
 vm.runInNewContext(readFileSync(new URL('../finance/pocketsmith-import.js',import.meta.url),'utf8'),{window:root,CustomEvent:class{},setTimeout,Date});return{api:root.PocketSmithImporter,model,stored};}
const snapshot=balance=>({complete:true,full:true,generatedAt:'2026-09-29T00:00:00Z',accounts:[{id:1,title:'Everyday',currentBalance:balance,currentBalanceDate:'2026-09-29',currencyCode:'AUD'}],transactions:[]});
test('import stores bank snapshot and unexplained difference without rewriting history',async()=>{const r=runtime();const result=await r.api.apply(snapshot(150));assert.equal(result.status,'ok');assert.equal(r.model.ACCTS[0].openBal,100);assert.equal(r.model.ACCTS[0].reconciliation.difference,60);assert.equal(vm.runInContext("balance('everyday')",r.model),150);assert.equal(r.stored.has('lifehub_finance_pending_commit'),false);});
test('import rejects null balance without mutations or saved cursor',async()=>{const r=runtime();assert.equal((await r.api.apply(snapshot(null))).status,'error');assert.equal(r.model.ACCTS[0].openBal,100);assert.equal(r.model.ACCTS[0].sourceBalance,undefined);});
test('failed second write rolls back both disk and in-memory account changes',async()=>{const r=runtime(true);const original=r.stored.get('fin_accounts');assert.equal((await r.api.apply({...snapshot(150),transactions:[{id:2,transactionAccountId:1,date:'2026-09-29',amount:-2,currencyCode:'AUD',payee:'Dummy'}]})).status,'error');assert.equal(r.stored.get('fin_accounts'),original);assert.equal(r.model.ACCTS[0].sourceBalance,undefined);});
test('attention result does not advance the client cursor',async()=>{const values=new Map([['finance_pocketsmith_app_token','dummy']]);const win={addEventListener(){},PocketSmithImporter:{apply:async()=>({status:'attention',detail:'Needs mapping'})}};vm.runInNewContext(readFileSync(new URL('../finance/pocketsmith-client.js',import.meta.url),'utf8'),{window:win,document:{dispatchEvent(){},addEventListener(){}},CustomEvent:class{},AbortSignal,Date,localStorage:{getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)},fetch:async()=>({ok:true,json:async()=>snapshot(100)})});await assert.rejects(win.PocketSmithFinance.syncNow(true),/Needs mapping/);assert.equal(values.has('finance_pocketsmith_last_sync'),false);});
test('malformed upstream response is an error, never an empty successful snapshot',async()=>{const worker=(await import('../finance/pocketsmith-sync/worker.js')).default;const original=global.fetch;try{global.fetch=async u=>({ok:true,json:async()=>String(u).endsWith('/me')?{id:1}:String(u).includes('transaction_accounts')?[]:{bad:true}});const res=await worker.fetch(new Request('https://test/snapshot',{headers:{Origin:'https://jaimk8365.github.io',Authorization:'Bearer dummy'}}),{APP_SYNC_TOKEN:'dummy',POCKETSMITH_DEVELOPER_KEY:'dummy'});assert.equal(res.status,502);}finally{global.fetch=original;}});
test('backfilled history does not alter a newer confirmed bank balance',async()=>{const r=runtime();await r.api.apply(snapshot(150));r.model.TXNS.push({id:'older',acct:'everyday',date:'2026-09-01',amount:-20});assert.equal(vm.runInContext("balance('everyday')",r.model),150);});
test('recovery journal uses separate tab storage instead of duplicating the ledger quota',async()=>{const r=runtime(),journal=new Map(),markers=[];r.model.sessionStorage={getItem:k=>journal.get(k)??null,setItem:(k,v)=>journal.set(k,v),removeItem:k=>journal.delete(k)};const original=r.model.localStorage.setItem;r.model.localStorage.setItem=(k,v)=>{if(k==='lifehub_finance_pending_commit')markers.push(JSON.parse(v));original(k,v);};assert.equal((await r.api.apply(snapshot(150))).status,'ok');assert.deepEqual(markers,[{version:2,storage:'session'}]);assert.equal(journal.size,0);});

test('unchanged atomic saves require no journal or quota headroom',()=>{const r=runtime();r.model.localStorage.setItem=()=>{throw Error('quota');};assert.doesNotThrow(()=>vm.runInContext('saveAtomic({fin_accounts:ACCTS,fin_txns:TXNS})',r.model));});
test('atomic save will not overwrite an interrupted recovery journal',()=>{const r=runtime();r.stored.set('lifehub_finance_pending_commit','{"existing":"evidence"}');assert.throws(()=>vm.runInContext('saveAtomic({fin_txns:[]})',r.model),/interrupted/);assert.equal(r.stored.get('lifehub_finance_pending_commit'),' {"existing":"evidence"}'.trim());});
test('failed rollback keeps the journal for recovery',()=>{const r=runtime();let calls=0;const setter=r.model.localStorage.setItem;r.model.localStorage.setItem=(k,v)=>{if(k!=='lifehub_finance_pending_commit'&&++calls>1)throw Error('quota');setter(k,v);};assert.throws(()=>vm.runInContext('saveAtomic({fin_accounts:[],fin_txns:[{id:"larger",note:"new"}]})',r.model));assert.equal(r.stored.has('lifehub_finance_pending_commit'),true);});
test('bank importer waits for durable completion and rolls back on asynchronous failure',async()=>{
 const r=runtime();let rejectSave;const gate=new Promise((_,reject)=>{rejectSave=reject;});r.model.window.FinanceStore={save:()=>gate};
 let done=false;const importing=r.api.apply(snapshot(150)).then(result=>{done=true;return result;});await new Promise(resolve=>setTimeout(resolve,0));assert.equal(done,false);
 rejectSave(new Error('Durable storage unavailable'));const result=await importing;assert.equal(result.status,'error');assert.equal(r.model.ACCTS[0].openBal,100);assert.equal(r.model.ACCTS[0].sourceBalance,undefined);assert.equal(r.model.TXNS.length,1);
});
test('invalid bank snapshots identify the affected account and field without revealing the balance',async()=>{
 const r=runtime(),data=snapshot(150);data.accounts[0].currentBalanceDate=null;const result=await r.api.apply(data);
 assert.equal(result.status,'error');assert.match(result.detail,/Everyday: missing valid balance date/);assert.doesNotMatch(result.detail,/150/);assert.equal(r.model.ACCTS[0].sourceBalance,undefined);
});
test('currency validation accepts lowercase AUD but still rejects foreign currencies',async()=>{
 const r=runtime(),data=snapshot(150);data.accounts[0].currencyCode='aud';assert.equal((await r.api.apply(data)).status,'ok');data.accounts[0].currencyCode='USD';assert.match((await r.api.apply(data)).detail,/unsupported currency/);
});
test('batch mapping rejects duplicate destinations and saves a complete swap without importing',async()=>{
 const r=runtime();r.model.ACCTS.push({id:'bills',name:'Bills',openBal:200});const data=snapshot(150);data.accounts.push({...data.accounts[0],id:2,title:'Bills'});await r.api.apply(data);
 await assert.rejects(r.api.setMappings({'1':'everyday','2':'everyday'}),/same Finance account/);assert.equal(r.stored.has(r.api.MAP_KEY),false);
 await r.api.setMappings({'1':'bills','2':'everyday'});assert.deepEqual(JSON.parse(r.stored.get(r.api.MAP_KEY)),{'1':'bills','2':'everyday'});assert.equal(r.model.ACCTS[0].pocketSmithAccountId,'1','saving mapping must not reimport the ledger');
 await assert.rejects(r.api.setMappings({'1':'bills','2':''}),/every bank account/);
});
