import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../src/finance.html',import.meta.url),'utf8');
function fn(name){const lines=source.split('\n'),i=lines.findIndex(l=>l.startsWith(`function ${name}(`));if(lines[i].endsWith('}'))return lines[i];return lines.slice(i,lines.findIndex((l,j)=>j>i&&l==='}')+1).join('\n');}
function runtime(fail=false){const stored=new Map([['fin_accounts',JSON.stringify([{id:'everyday',name:'Everyday',openBal:100}])],['fin_txns',JSON.stringify([{id:'t',acct:'everyday',date:'2026-09-28',amount:-10}])]]);let failed=false;
 const storage={getItem:k=>stored.get(k)??null,setItem(k,v){if(fail&&k==='fin_txns'&&!failed){failed=true;throw Error('quota');}stored.set(k,v);},removeItem:k=>stored.delete(k)};
 const model=vm.createContext({ACCTS:JSON.parse(stored.get('fin_accounts')),TXNS:JSON.parse(stored.get('fin_txns')),K_ACCTS:'fin_accounts',K_TXNS:'fin_txns',window:{},localStorage:storage,todayISO:()=> '2026-09-29'});
 vm.runInContext(fn('saveAtomic')+';'+fn('balance')+';function acctById(id){return ACCTS.find(x=>x.id===id)}',model);
 const w=model.window;w.eval=code=>vm.runInContext(code,model);const root={document:{getElementById:()=>({contentWindow:w}),dispatchEvent(){}},localStorage:{getItem:()=>null}};
 vm.runInNewContext(readFileSync(new URL('../finance/pocketsmith-import.js',import.meta.url),'utf8'),{window:root,CustomEvent:class{},setTimeout,Date});return{api:root.PocketSmithImporter,model,stored};}
const snapshot=balance=>({complete:true,full:true,generatedAt:'2026-09-29T00:00:00Z',accounts:[{id:1,title:'Everyday',currentBalance:balance,currentBalanceDate:'2026-09-29',currencyCode:'AUD'}],transactions:[]});
test('import stores bank snapshot and unexplained difference without rewriting history',async()=>{const r=runtime();const result=await r.api.apply(snapshot(150));assert.equal(result.status,'ok');assert.equal(r.model.ACCTS[0].openBal,100);assert.equal(r.model.ACCTS[0].reconciliation.difference,60);assert.equal(vm.runInContext("balance('everyday')",r.model),150);assert.equal(r.stored.has('lifehub_finance_pending_commit'),false);});
test('import rejects null balance without mutations or saved cursor',async()=>{const r=runtime();assert.equal((await r.api.apply(snapshot(null))).status,'error');assert.equal(r.model.ACCTS[0].openBal,100);assert.equal(r.model.ACCTS[0].sourceBalance,undefined);});
test('failed second write rolls back both disk and in-memory account changes',async()=>{const r=runtime(true);const original=r.stored.get('fin_accounts');assert.equal((await r.api.apply(snapshot(150))).status,'error');assert.equal(r.stored.get('fin_accounts'),original);assert.equal(r.model.ACCTS[0].sourceBalance,undefined);});
test('attention result does not advance the client cursor',async()=>{const values=new Map([['finance_pocketsmith_app_token','dummy']]);const win={addEventListener(){},PocketSmithImporter:{apply:async()=>({status:'attention',detail:'Needs mapping'})}};vm.runInNewContext(readFileSync(new URL('../finance/pocketsmith-client.js',import.meta.url),'utf8'),{window:win,document:{dispatchEvent(){},addEventListener(){}},CustomEvent:class{},AbortSignal,Date,localStorage:{getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)},fetch:async()=>({ok:true,json:async()=>snapshot(100)})});await assert.rejects(win.PocketSmithFinance.syncNow(true),/Needs mapping/);assert.equal(values.has('finance_pocketsmith_last_sync'),false);});
test('malformed upstream response is an error, never an empty successful snapshot',async()=>{const worker=(await import('../finance/pocketsmith-sync/worker.js')).default;const original=global.fetch;try{global.fetch=async u=>({ok:true,json:async()=>String(u).endsWith('/me')?{id:1}:String(u).includes('transaction_accounts')?[]:{bad:true}});const res=await worker.fetch(new Request('https://test/snapshot',{headers:{Origin:'https://jaimk8365.github.io',Authorization:'Bearer dummy'}}),{APP_SYNC_TOKEN:'dummy',POCKETSMITH_DEVELOPER_KEY:'dummy'});assert.equal(res.status,502);}finally{global.fetch=original;}});
test('backfilled history does not alter a newer confirmed bank balance',async()=>{const r=runtime();await r.api.apply(snapshot(150));r.model.TXNS.push({id:'older',acct:'everyday',date:'2026-09-01',amount:-20});assert.equal(vm.runInContext("balance('everyday')",r.model),150);});
