/* On-device help and review presentation. Persistence stays with the Finance page. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FinanceGuide=api;})(typeof globalThis==='object'?globalThis:this,function(){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(v);
 const steps=[
  ['🏠','Start with Overview','A quick picture, not a spending permission slip.','Recorded cash includes savings and bill money. Bills due uses your saved calendar. Net position excludes property and other assets.','today','Show Overview'],
  ['🏦','Check Accounts','A bank balance and a transaction history are different things.','Check the bank balance date. Matching accounts tells imports where to go. It does not reconcile old transactions.','accounts','Show Accounts'],
  ['🗺️','Explore Money Map','Choose Week, Fortnight, Month to date or Year to date.','Open a spending group for examples. Transfers between your accounts are excluded. Account routes show a plan; this app does not move money.','money-map','Show Money Map'],
  ['🛡️','Understand the warnings','Check data first means the app is withholding an estimate.','Awaiting review does not mean no income. Partial history means totals omit unchecked records. Safe to Spend also needs recent reviewed history and a complete repayment plan.','attention','Explain my warnings'],
  ['📅','Your easy routine','Open → check updates → look at upcoming bills.','Feed ✓ means the bank import completed. Synced means private sync completed. If Change not saved appears, keep the page open. Download an encrypted recovery backup before major edits.','bills','Show Bills']
 ];
 function attentionModel(evidence={accounts:[]}){return (evidence.accounts||[]).map(a=>({...a,issues:[...(!a.current?['Refresh the dated bank balance.']:[]),...(a.malformed?[a.malformed+' records have an invalid amount or date.']:[]),...(!a.balanced?[Number.isFinite(a.difference)?'Bank balance and ledger differ by '+money(a.difference)+'.':'No bank-to-ledger comparison is available.']:[]),...(a.unreviewed?[a.unreviewed+' transaction records still need checking.']:[])]}));}
 const button=(text,action,value='',kind='ghost')=>'<button class="btn '+kind+'" data-guide-action="'+action+'" data-guide-value="'+esc(value)+'">'+text+'</button>';
 function renderTour(index=0,partner=false){index=Math.max(0,Math.min(steps.length-1,index));const [icon,title,subtitle,body,route,label]=steps[index];return '<div class="fg-guide"><h2>📖 Your visual Money guide</h2><p>One small step at a time. Come back using Guide whenever you need it.</p><nav class="fg-dots" aria-label="Guide steps">'+steps.map((s,i)=>'<button data-guide-action="step" data-guide-value="'+i+'" aria-label="Step '+(i+1)+': '+esc(s[1])+'" '+(i===index?'aria-current="step"':'')+'>'+s[0]+'</button>').join('')+'</nav><p class="fg-count" role="status">Step '+(index+1)+' of '+steps.length+'</p><article class="fg-feature"><span class="fg-icon" aria-hidden="true">'+icon+'</span><h3>'+title+'</h3><p><b>'+subtitle+'</b></p><p>'+body+'</p>'+(partner?'<p>Matthew’s view uses shared household information; Jaimi’s private spending is excluded. Check the shared update date. Resolve source-record warnings in Jaimi’s app.</p>':'')+button(label,'route',route,'dark')+'</article><div class="fg-controls">'+(index?button('← Back','step',index-1):'')+(index<steps.length-1?button('Next →','step',index+1):button('Finish guide','close'))+'</div></div>';}
 function renderAttention(evidence={},partner=false){
  if(partner)return '<div class="fg-guide"><h2>Check the shared records</h2><p>Jaimi’s app has the source records. Review them there before relying on spending estimates.</p>'+button('Show shared Accounts','route','accounts')+'</div>';
  const accounts=attentionModel(evidence),pending=accounts.filter(a=>a.issues.length),checked=accounts.filter(a=>!a.issues.length);
  return '<div class="fg-guide"><h2>Let’s check your records</h2><p>Work through one account at a time. This warning does not mean you have run out of money.</p>'+pending.map(a=>'<article class="fg-account"><h3>'+esc(a.name)+'</h3><p>'+esc(a.unreviewed?a.unreviewed+' transaction'+(a.unreviewed===1?'':'s')+' to check':a.malformed?a.malformed+' records need correcting':!a.current?'Bank balance needs updating':'Balance difference '+money(a.difference))+'</p>'+button(a.unreviewed||a.malformed?'Review transactions':'Open account',a.unreviewed||a.malformed?'records':'account',a.id,'dark')+'<details><summary>Why this account needs checking</summary><p>Bank balance date: '+esc(a.date||'not available')+'</p><ul>'+a.issues.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>'+button('Open account','account',a.id)+'</details></article>').join('')+(pending.length?'':'<p>✓ The three operating accounts are checked.</p>')+(evidence.conflicts?'<article class="fg-account"><h3>Conflicting versions</h3><p>'+evidence.conflicts+' saved versions need a decision.</p>'+button('Review versions','recovery','','dark')+'</article>':'')+'<details class="fg-feature"><summary>Already checked &amp; recovery options</summary>'+checked.map(a=>'<p>'+esc(a.name)+' · ✓ Checked</p>').join('')+'<p>'+(evidence.conflicts?'':'No sync conflicts are recorded. ')+'$0.00 differences are already balanced; they are not conflicts.</p><p>A balance difference is not automatically money owed. Compare your statement and correct confirmed errors; do not change an opening balance just to hide it.</p><p>Keep an encrypted recovery copy before correcting records.</p>'+button('Download private recovery backup','backup')+button('Open data and recovery','recovery')+'</details><p>Confirmed transactions leave the review list and stay in account history. Spending estimates remain paused while other records or balance differences need checking.</p>'+button('Recheck my data','attention')+'</div>';
 }
 function reviewRows(rows=[],accountId){return rows.filter(t=>t.acct===accountId&&!t.deleted&&(t.needsReview||t.needsDetails||t.sourceMissing||t.amount==null||String(t.amount).trim()===''||!Number.isFinite(+t.amount)||!/^\d{4}-\d{2}-\d{2}$/.test(t.date||'')||!Number.isFinite(Date.parse(t.date+'T12:00:00Z'))||new Date(t.date+'T12:00:00Z').toISOString().slice(0,10)!==t.date)).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));}
 function renderRecords(rows,offset=0){if(!rows.length)return '<div class="fg-guide"><h2>All checked</h2><p>No transactions remain in this review list. Your confirmed entries are saved in account history.</p>'+button('Back to data checks','attention')+'</div>';const page=rows.slice(offset,offset+10);return '<div class="fg-guide"><h2>Records to check</h2><p>Showing '+(rows.length?offset+1:0)+'–'+Math.min(offset+10,rows.length)+' of '+rows.length+'. Check each against your bank statement, then save and confirm. Confirmed entries stay in account history.</p>'+page.map((t,i)=>'<article class="fg-account"><h3>'+esc(t.note||'Transaction')+'</h3><p>'+esc(t.date)+' · '+(t.amount!=null&&String(t.amount).trim()!==''&&Number.isFinite(+t.amount)?money(+t.amount):'Invalid amount')+'</p><p>'+[t.needsReview?'Category needs review':'',t.needsDetails?'Details missing':'',t.sourceMissing?'Missing from the latest source import; verify with your statement':''].filter(Boolean).join(' · ')+'</p>'+button('Open existing transaction editor','edit',offset+i)+'</article>').join('')+'<div class="fg-controls">'+(offset?button('← Previous 10','page',offset-10):'')+(offset+10<rows.length?button('Next 10 →','page',offset+10):'')+'</div>'+button('Back to data checks','attention')+'</div>';}
 function open(options,mode='tour'){
  const {host,show,close,partner=false,readEvidence=()=>({accounts:[]}),transactions=()=>[],navigate,account,edit,backup,recovery}=options;let rows=[],accountId=null,shown=false;
  const paint=html=>{host.onclick=handle;host.innerHTML='<button class="close" data-guide-action="close" aria-label="Close guide">✕</button>'+html;if(!shown){show();shown=true;}else{host.setAttribute('aria-label',host.querySelector('h2')?.textContent||'Money guide');host.querySelector('button')?.focus();}host.scrollTop=0;};
  const attention=()=>paint(renderAttention(readEvidence(),partner));
  const handle=e=>{const b=e.target.closest('[data-guide-action]');if(!b||!host.contains(b))return;const value=b.dataset.guideValue;switch(b.dataset.guideAction){case 'close':close();host.onclick=null;break;case 'step':paint(renderTour(+value,partner));break;case 'attention':attention();break;case 'route':if(value==='attention')attention();else{host.onclick=null;close();navigate(value);}break;case 'account':host.onclick=null;close();account(value);break;case 'records':accountId=value;rows=reviewRows(transactions(),accountId);paint(renderRecords(rows));break;case 'page':paint(renderRecords(rows,Math.max(0,+value||0)));break;case 'edit':if(rows[+value]){const offset=Math.floor((+value)/10)*10;host.onclick=null;edit(rows[+value].id,()=>{show();rows=reviewRows(transactions(),accountId);paint(renderRecords(rows,Math.min(offset,Math.max(0,Math.ceil(rows.length/10)-1)*10)));});}break;case 'backup':backup();break;case 'recovery':host.onclick=null;recovery();break;}};
  host.onclick=handle;if(mode==='attention')attention();else paint(renderTour(0,partner));
 }
 function confirmRecord(record,changes={},at){
  const t={...record,...changes},stamp=/^\d{4}-\d{2}-\d{2}$/.test(t.date||'')?Date.parse(t.date+'T12:00:00Z'):NaN;
  if(t.amount==null||String(t.amount).trim()===''||!Number.isFinite(+t.amount)||!Number.isFinite(stamp)||new Date(stamp).toISOString().slice(0,10)!==t.date||!t.acct||!t.cat||!String(t.note||'').trim())throw Error('Check the amount, date, account, category and description first.');
  if(/pending/i.test(t.sourceStatus||''))throw Error('This transaction is pending. Refresh the feed after it is posted.');
  if(t.src==='balance-adjustment')throw Error('This is a balance placeholder. Replace it with verified transactions before confirming.');
  return {...t,needsReview:false,needsDetails:false,sourceMissing:false,...(record.sourceMissing?{sourceMissingConfirmed:true}:{}),reviewedAt:at,...(t.pocketsmithId?{categoryOverride:true,noteOverride:true}:{})};
 }
 return{attentionModel,renderTour,renderAttention,reviewRows,renderRecords,confirmRecord,open};
});
