/* On-device help only. This module never saves, approves or changes financial records. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FinanceGuide=api;})(typeof globalThis==='object'?globalThis:this,function(){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(v);
 const steps=[
  ['🏠','Start with Overview','A quick picture, not a spending permission slip.','Recorded cash includes savings and bill money. Bills due uses your saved calendar. Net position excludes property and other assets.','today','Show Overview'],
  ['🏦','Check Accounts','A bank balance and a transaction history are different things.','Check the bank balance date. Matching accounts tells imports where to go. It does not reconcile old transactions.','accounts','Show Accounts'],
  ['🗺️','Explore Money Map','Choose Week, Fortnight, Month to date or Year to date.','Open a spending group for examples. Transfers between your accounts are excluded. Account routes show a plan; this app does not move money.','money-map','Show Money Map'],
  ['🛡️','Understand the warnings','Check data first means the app is withholding an estimate.','Awaiting review does not mean no income. Partial history means totals omit unchecked records. Safe to Spend also needs recent reviewed history and a complete repayment plan.','attention','Explain my warnings'],
  ['📅','Your easy routine','Open → check updates → look at upcoming bills.','Feed ✓ means the bank import completed. Synced means private sync completed. If Change not saved appears, keep the page open. Download an encrypted recovery backup before major edits.','bills','Show Bills']
 ];
 function attentionModel(evidence={accounts:[]}){return (evidence.accounts||[]).map(a=>({...a,issues:[...(!a.current?['Refresh the dated bank balance.']:[]),...(a.malformed?[a.malformed+' records have an invalid amount or date.']:[]),...(!a.balanced?[Number.isFinite(a.difference)?'Bank balance and ledger differ by '+money(a.difference)+'.':'No bank-to-ledger comparison is available.']:[]),...(a.unreviewed?[a.unreviewed+' transaction records still need checking.']:[])]}));}
 const button=(text,action,value='',kind='ghost')=>'<button class="btn '+kind+'" data-guide-action="'+action+'" data-guide-value="'+esc(value)+'">'+text+'</button>';
 function renderTour(index=0,partner=false){index=Math.max(0,Math.min(steps.length-1,index));const [icon,title,subtitle,body,route,label]=steps[index];return '<div class="fg-guide"><h2>📖 Your visual Money guide</h2><p>One small step at a time. Come back using Guide whenever you need it.</p><nav class="fg-dots" aria-label="Guide steps">'+steps.map((s,i)=>'<button data-guide-action="step" data-guide-value="'+i+'" aria-label="Step '+(i+1)+': '+esc(s[1])+'" '+(i===index?'aria-current="step"':'')+'>'+s[0]+'</button>').join('')+'</nav><p class="fg-count" role="status">Step '+(index+1)+' of '+steps.length+'</p><article class="fg-feature"><span class="fg-icon" aria-hidden="true">'+icon+'</span><h3>'+title+'</h3><p><b>'+subtitle+'</b></p><p>'+body+'</p>'+(partner?'<p>Matthew’s view uses shared household information; Jaimi’s private spending is excluded. Check the shared update date. Resolve source-record warnings in Jaimi’s app.</p>':'')+button(label,'route',route,'dark')+'</article><div class="fg-controls">'+(index?button('← Back','step',index-1):'')+(index<steps.length-1?button('Next →','step',index+1):button('Finish guide','close'))+'</div></div>';}
 function renderAttention(evidence,partner=false){if(partner)return '<div class="fg-guide"><h2>Why spending advice is paused</h2><div class="fg-feature"><span class="fg-icon">🛡️</span><p>Shared figures come from Jaimi’s app. Check its update date. Unresolved balances, unchecked records or missing plan details can pause the spending estimate.</p><p>Open Guide → Explain my warnings in Jaimi’s app for the live account checklist. This view cannot certify or repair the source ledger.</p></div>'+button('Show shared Accounts','route','accounts')+'</div>';
 const accounts=attentionModel(evidence);return '<div class="fg-guide"><h2>Let’s check your data</h2><p>This is a data check, not a message that you have run out of money. These checks use your current records.</p><div class="fg-feature"><b>1 · Keep a recovery copy</b><p>Save the encrypted backup before correcting records.</p>'+button('Download private recovery backup','backup')+'</div><h3>2 · Check the three operating accounts</h3>'+accounts.map(a=>'<article class="fg-account"><h4>'+esc(a.name)+' · '+(a.trusted?'✓ Checked':'Needs checking')+'</h4><p>Bank balance date: '+esc(a.date||'not available')+'</p>'+(a.issues.length?'<ul>'+a.issues.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>':'<p>Balance and recorded history checks pass.</p>')+button('Open account','account',a.id)+(a.unreviewed||a.malformed?button('Show records to check','records',a.id):'')+'</article>').join('')+'<div class="fg-feature"><b>How to resolve a balance difference</b><p>Compare the dated bank balance with the account history. Check missing or duplicated entries, wrong amounts, dates and accounts against your statement. Correct only confirmed errors. Refreshing the feed may bring missing entries, but cannot certify older history.</p><p>Do not change an opening balance just to make the difference disappear. A difference is not automatically spending or money owed.</p></div><h3>3 · Recheck</h3><p>'+(evidence.conflicts?evidence.conflicts+' sync conflicts also need review.':'No sync conflicts are recorded.')+' $0.00 differences are already balanced; they are not conflicts.</p><p>When all three accounts pass and there are no conflicts, the yellow data warning clears automatically. Safe to Spend can still pause for missing recent history, repayment amounts or overlapping loan bills.</p>'+button('Open data and recovery','recovery')+button('Recheck my data','attention')+'</div>';}
 function reviewRows(rows=[],accountId){return rows.filter(t=>t.acct===accountId&&!t.deleted&&(t.needsReview||t.needsDetails||t.sourceMissing||t.amount==null||String(t.amount).trim()===''||!Number.isFinite(+t.amount)||!/^\d{4}-\d{2}-\d{2}$/.test(t.date||'')||!Number.isFinite(Date.parse(t.date+'T12:00:00Z'))||new Date(t.date+'T12:00:00Z').toISOString().slice(0,10)!==t.date)).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));}
 function renderRecords(rows,offset=0){const page=rows.slice(offset,offset+10);return '<div class="fg-guide"><h2>Records to check</h2><p>Showing '+(rows.length?offset+1:0)+'–'+Math.min(offset+10,rows.length)+' of '+rows.length+'. Check each against your bank statement before editing. Saving a category does not resolve missing source data or prove a balance difference.</p>'+page.map((t,i)=>'<article class="fg-account"><h3>'+esc(t.note||'Transaction')+'</h3><p>'+esc(t.date)+' · '+(t.amount!=null&&String(t.amount).trim()!==''&&Number.isFinite(+t.amount)?money(+t.amount):'Invalid amount')+'</p><p>'+[t.needsReview?'Category needs review':'',t.needsDetails?'Details missing':'',t.sourceMissing?'Missing from the latest source import; verify with your statement':''].filter(Boolean).join(' · ')+'</p>'+button('Open existing transaction editor','edit',offset+i)+'</article>').join('')+'<div class="fg-controls">'+(offset?button('← Previous 10','page',offset-10):'')+(offset+10<rows.length?button('Next 10 →','page',offset+10):'')+'</div>'+button('Back to data checks','attention')+'</div>';}
 function open(options,mode='tour'){
  const {host,show,close,partner=false,readEvidence=()=>({accounts:[]}),transactions=()=>[],navigate,account,edit,backup,recovery}=options;let rows=[],accountId=null,shown=false;
  const paint=html=>{host.innerHTML='<button class="close" data-guide-action="close" aria-label="Close guide">✕</button>'+html;if(!shown){show();shown=true;}else{host.setAttribute('aria-label',host.querySelector('h2')?.textContent||'Money guide');host.querySelector('button')?.focus();}host.scrollTop=0;};
  const attention=()=>paint(renderAttention(readEvidence(),partner));
  host.onclick=e=>{const b=e.target.closest('[data-guide-action]');if(!b||!host.contains(b))return;const value=b.dataset.guideValue;switch(b.dataset.guideAction){case 'close':close();host.onclick=null;break;case 'step':paint(renderTour(+value,partner));break;case 'attention':attention();break;case 'route':if(value==='attention')attention();else{host.onclick=null;close();navigate(value);}break;case 'account':host.onclick=null;close();account(value);break;case 'records':accountId=value;rows=reviewRows(transactions(),accountId);paint(renderRecords(rows));break;case 'page':paint(renderRecords(rows,Math.max(0,+value||0)));break;case 'edit':if(rows[+value]){host.onclick=null;edit(rows[+value].id);}break;case 'backup':backup();break;case 'recovery':host.onclick=null;recovery();break;}};
  if(mode==='attention')attention();else paint(renderTour(0,partner));
 }
 return{attentionModel,renderTour,renderAttention,reviewRows,renderRecords,open};
});
